version: '3'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: always
    ports:
      - "3010:3001"
    dns:
      - 192.168.23.102
      - 192.168.23.1

    volumes:
      - /mnt/uptime-kuma:/app/data:rw
